**Sacamos información de los jugadores**

In [1]:
import requests
import pandas as pd

In [10]:
jugadores = {"nombres": [], "apellidos": [], "equipo": []}
for pagina in range(1, 3):
        
    res_jugadores = requests.get(f"https://www.balldontlie.io/api/v1/players?per_page=100?page={pagina}")
    res_jugadores = res_jugadores.json()

    
    for jugador in res_jugadores["data"]:
        jugadores["nombres"].append(jugador["first_name"])
        jugadores["apellidos"].append(jugador["last_name"])
        jugadores["equipo"].append(jugador["team"]["full_name"])    

df_jugadores = pd.DataFrame(jugadores)
df_jugadores

     nombres apellidos                  equipo
0        Ike  Anigbogu          Indiana Pacers
1        Ron     Baker         New York Knicks
2     Jabari      Bird          Boston Celtics
3    MarShon    Brooks       Memphis Grizzlies
4    Lorenzo     Brown         Toronto Raptors
..       ...       ...                     ...
195     Brad    Lohaus         Milwaukee Bucks
196     Mike     Brown               Utah Jazz
197    Kenny    Battle            Phoenix Suns
198    Danny     Young  Portland Trail Blazers
199    Larry     Smith         Houston Rockets

[200 rows x 3 columns]

**Extrae la información de 200 partidos**

In [29]:
partidos = {"equipo_local": [], "equipo_visitante": [], "puntos_local": [], "puntos_visitante": [], "temporada": []}

for pagina in range(1, 3):
        
    res_partidos = requests.get(f"https://www.balldontlie.io/api/v1/games?per_page=100?page={pagina}")
    res_partidos = res_partidos.json()

    
    for partido in res_partidos["data"]:
        partidos["equipo_local"].append(partido["home_team"]["full_name"])
        partidos["equipo_visitante"].append(partido["visitor_team"]["full_name"])
        partidos["puntos_local"].append(partido["home_team_score"])  
        partidos["puntos_visitante"].append(partido["visitor_team_score"])   
        partidos["temporada"].append(partido["season"]) 

df_partidos = pd.DataFrame(partidos)
df_partidos

,equipo_local,equipo_visitante,puntos_local,puntos_visitante,temporada
0,Boston Celtics,Charlotte Hornets,126,94,2018
1,Boston Celtics,LA Clippers,112,123,2018
2,Philadelphia 76ers,Denver Nuggets,117,110,2018
3,Washington Wizards,Cleveland Cavaliers,119,106,2018
4,Sacramento Kings,Miami Heat,102,96,2018
...,...,...,...,...,...
195,Washington Wizards,Indiana Pacers,112,119,2018
196,Brooklyn Nets,Portland Trail Blazers,99,113,2018
197,Cleveland Cavaliers,Phoenix Suns,111,98,2018
198,Brooklyn Nets,Washington Wizards,116,125,2018
199,Indiana Pacers,New Orleans Pelicans,126,111,2018