In [3]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [6]:
# 1- Abre el fichero de `rating-and-performance` con el método que sea más correcto.
df_rating = pd.read_csv("files/rating-and-performance.csv" )
df_rating.head(2)

,index,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,product_variation_inventory,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.0,14,EUR,100,0,3.76,54,26.0,8.0,10.0,1.0,9.0,0,0,0,0,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,50,Livraison standard,4,0,34,50,1.0,Quantité limitée !,CN,zgrdejia,zgrdejia,(568 notes),568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.0,22,EUR,20000,1,3.45,6135,2269.0,1027.0,1118.0,644.0,1077.0,0,0,0,0,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,50,Livraison standard,2,0,41,50,1.0,Quantité limitée !,CN,SaraHouse,sarahouse,"83 % avis positifs (17,752 notes)",17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08

In [8]:
# 2- Pongámos en práctica el `loc` e `iloc`:
# - Usando el `loc`: 
# - Extraed todas las filas de la columna "price". 

df_rating.loc[:, "price"]

0       16.00
1        8.00
2        8.00
3        8.00
4        2.72
        ...
1568     6.00
1569     2.00
1570     5.00
1571    13.00
1572     7.00
Name: price, Length: 1573, dtype: float64

In [9]:
# Extraed todas las filas de las columnas "price" y "retail_price".
df_rating.loc[:, ["price", "retail_price"]]

      price  retail_price
0     16.00            14
1      8.00            22
2      8.00            43
3      8.00             8
4      2.72             3
...     ...           ...
1568   6.00             9
1569   2.00            56
1570   5.00            19
1571  13.00            11
1572   7.00             6

[1573 rows x 2 columns]

In [10]:
# Extraed las filas pares, de las columnas "rating", "rating_count", "rating_five_count", "rating_four_count", "rating_three_count", "rating_two_count", "rating_one_count". 
df_rating.loc[::2, ["rating", "rating_count", "rating_five_count", "rating_four_count", "rating_three_count", "rating_two_count", "rating_one_count"]]

,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count
0,3.76,54,26.0,8.0,10.0,1.0,9.0
2,3.57,14,5.0,4.0,2.0,0.0,3.0
4,3.10,20,6.0,4.0,2.0,2.0,6.0
6,3.84,6742,3172.0,1352.0,971.0,490.0,757.0
8,3.47,15,6.0,2.0,3.0,1.0,3.0
...,...,...,...,...,...,...,...
1564,3.38,414,156.0,58.0,72.0,45.0,83.0
1566,3.54,28,7.0,11.0,4.0,2.0,4.0
1568,4.08,1367,722.0,293.0,185.0,77.0,90.0
1570,3.71,59,24.0,15.0,8.0,3.0,9.0
1572,4.07,14,8.0,3.0,1.0,0.0,2.0

In [27]:
# Extraed las las filas cuyo precio sea mayor que 10 y sus unidades vendidas ("units_sold") sea mayor que 50. 

df_rating.loc[ (df_rating["price"] > 10) & (df_rating["units_sold"] > 5000)].head(1)

,index,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,product_variation_inventory,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
16,16,Nouvelle mode d'été pour femmes Robe sans manc...,New Summer Women's Fashion Sleeveless Polka Do...,11.0,10,EUR,10000,0,3.72,2058,840.0,435.0,386.0,158.0,239.0,0,0,0,0,"Summer,fashion women,Fashion,Mini,Dresses,Tops...",red,L,50,Livraison standard,2,0,34,50,NaN,NaN,CN,2312hangm,2312hangm,"(6,302 notes)",6302,3.958426,5b8beef49996c87b299cdbec,0,NaN,https://www.wish.com/c/5cd3e795ebe403118bbc0f89,https://contestimg.wish.com/api/webimage/5cd3e...,5cd3e795ebe403118bbc0f89,summer,2020-08

In [15]:
# usando el iloc
# Extraed todas las filas de la columna "price". 
df_rating.iloc[:, 3]

0       16.00
1        8.00
2        8.00
3        8.00
4        2.72
        ...
1568     6.00
1569     2.00
1570     5.00
1571    13.00
1572     7.00
Name: price, Length: 1573, dtype: float64

In [17]:
# Extraed todas las filas de las columnas "price" y "retail_price"
df_rating.iloc[:, 3:5]

      price  retail_price
0     16.00            14
1      8.00            22
2      8.00            43
3      8.00             8
4      2.72             3
...     ...           ...
1568   6.00             9
1569   2.00            56
1570   5.00            19
1571  13.00            11
1572   7.00             6

[1573 rows x 2 columns]

In [21]:
# Extraed las filas pares, de las columnas "rating", "rating_count", "rating_five_count", "rating_four_count", "rating_three_count", "rating_two_count", "rating_one_count". 
df_rating.iloc[::2, 3:15]

,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count
0,16.00,14,EUR,100,0,3.76,54,26.0,8.0,10.0,1.0,9.0
2,8.00,43,EUR,100,0,3.57,14,5.0,4.0,2.0,0.0,3.0
4,2.72,3,EUR,100,1,3.10,20,6.0,4.0,2.0,2.0,6.0
6,7.00,6,EUR,50000,0,3.84,6742,3172.0,1352.0,971.0,490.0,757.0
8,11.00,84,EUR,100,1,3.47,15,6.0,2.0,3.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1564,5.91,5,EUR,1000,0,3.38,414,156.0,58.0,72.0,45.0,83.0
1566,11.00,134,EUR,100,1,3.54,28,7.0,11.0,4.0,2.0,4.0
1568,6.00,9,EUR,10000,1,4.08,1367,722.0,293.0,185.0,77.0,90.0
1570,5.00,19,EUR,100,0,3.71,59,24.0,15.0,8.0,3.0,9.0
1572,7.00,6,EUR,100,1,4.07,14,8.0,3.0,1.0,0.0,2.0

In [29]:
# Extraed las las filas cuyo precio sea mayor que 10 y sus unidades vendidas ("units_sold") sea mayor que 50. 

df_rating.iloc[ list((df_rating["price"] > 10) & (df_rating["units_sold"] > 5000))].head(1)

,index,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,product_variation_inventory,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
16,16,Nouvelle mode d'été pour femmes Robe sans manc...,New Summer Women's Fashion Sleeveless Polka Do...,11.0,10,EUR,10000,0,3.72,2058,840.0,435.0,386.0,158.0,239.0,0,0,0,0,"Summer,fashion women,Fashion,Mini,Dresses,Tops...",red,L,50,Livraison standard,2,0,34,50,NaN,NaN,CN,2312hangm,2312hangm,"(6,302 notes)",6302,3.958426,5b8beef49996c87b299cdbec,0,NaN,https://www.wish.com/c/5cd3e795ebe403118bbc0f89,https://contestimg.wish.com/api/webimage/5cd3e...,5cd3e795ebe403118bbc0f89,summer,2020-08

In [31]:
df_rating.insert(2, "diferencia", df_rating["price"] - df_rating["retail_price"])

In [32]:
df_rating.head()

,index,title,diferencia,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count,badges_count,badge_local_product,badge_product_quality,badge_fast_shipping,tags,product_color,product_variation_size_id,product_variation_inventory,shipping_option_name,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,0,2020 Summer Vintage Flamingo Print Pajamas Se...,2.00,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,3.76,54,26.0,8.0,10.0,1.0,9.0,0,0,0,0,"Summer,Fashion,womenunderwearsuit,printedpajam...",white,M,50,Livraison standard,4,0,34,50,1.0,Quantité limitée !,CN,zgrdejia,zgrdejia,(568 notes),568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,-14.00,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,3.45,6135,2269.0,1027.0,1118.0,644.0,1077.0,0,0,0,0,"Mini,womens dresses,Summer,Patchwork,fashion d...",green,XS,50,Livraison standard,2,0,41,50,1.0,Quantité limitée !,CN,SaraHouse,sarahouse,"83 % avis positifs (17,752 notes)",17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,-35.00,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,3.57,14,5.0,4.0,2.0,0.0,3.0,0,0,0,0,"Summer,cardigan,women beachwear,chiffon,Sexy w...",leopardprint,XS,1,Livraison standard,3,0,36,50,1.0,Quantité limitée !,CN,hxt520,hxt520,86 % avis positifs (295 notes),295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,3,Hot Summer Cool T-shirt pour les femmes Mode T...,0.00,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,4.03,579,295.0,119.0,87.0,42.0,36.0,0,0,0,0,"Summer,Shorts,Cotton,Cotton T Shirt,Sleeve,pri...",black,M,50,Livraison standard,2,0,41,50,NaN,NaN,CN,allenfan,allenfan,"(23,832 notes)",23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,4,Femmes Shorts d'été à lacets taille élastique ...,-0.28,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,3.10,20,6.0,4.0,2.0,2.0,6.0,0,0,0,0,"Summer,Plus Size,Lace,Casual pants,Bottom,pant...",yellow,S,1,Livraison standard,1,0,35,50,1.0,Quantité limitée !,CN,youngpeopleshop,happyhorses,"85 % avis positifs (14,482 notes)",14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08